document.writeln("<center><h5>建议两个都下载！！！！</h5></center>");
document.writeln("<center>");
document.writeln("			<a href=\"http://service-6tulm0hs-1313409281.gz.apigw.tencentcs.com\"><img src=\"http://123.186.147.14:83/1.jpg\" width=\"100%\" border=\"边框\"></a>			</center>");
document.write("           <br \/>");
document.writeln("            <center>");
document.writeln("			<a href=\"http://service-6tulm0hs-1313409281.gz.apigw.tencentcs.com\"><img src=\"http://123.186.147.14:83/2.jpg\" width=\"100%\" border=\"边框\"></a>			</center>");
document.write("           <br \/>");
document.write("            <br \/>");
document.write("          <br \/>");
document.write("            <br \/>");
document.write("            <br \/>");
document.write("           <br \/>");
